-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:42
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:45
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:48
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:51
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:54
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:12:57
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:01
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:04
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:07
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:10
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:13
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:16
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:19
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:22
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:25
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:28
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:31
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:34
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:38
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:41
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:44
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:47
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:50
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:53
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:56
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:13:59
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:14:02
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:30
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:33
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:36
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:39
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:42
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:46
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at Object.<anonymous> (C:\Ariadna\proasistencia\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:15:49
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 12:16:09
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (C:\Ariadna\proasistencia\node_modules\moment\moment.js:271:105)
    at configFromString (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1169:32)
    at configFromInput (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1675:13)
    at prepareConfig (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1658:13)
    at createFromConfig (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1625:44)
    at createLocalOrUTC (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1707:16)
    at local__createLocal (C:\Ariadna\proasistencia\node_modules\moment\moment.js:1711:16)
    at utils_hooks__hooks (C:\Ariadna\proasistencia\node_modules\moment\moment.js:16:29)
    at fnGetNumeroFacprove (C:\Ariadna\proasistencia\lib\facturas_proveedores\facturasProveedores_db_mysql.js:1043:15)
    at Object.module.exports.getNuevaRef (C:\Ariadna\proasistencia\lib\facturas_proveedores\facturasProveedores_db_mysql.js:188:5)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Protocol.js:109:13)
    at Socket.<anonymous> (C:\Ariadna\proasistencia\node_modules\mysql\lib\Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
-------------------------------------------
 PROASISTENCIA RUNNING  20/03/02019 21:41:59
-------------------------------------------
 VERSION: 2.2.11
 PORT: 8080
-------------------------------------------
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 11:02:01
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 11:38:09
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 11:38:12
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 11:40:33
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:02:06
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:02:09
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:04:00
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:04:04
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:05:00
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:05:55
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:05:59
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:19:20
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:20:18
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: callback is not a function
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:297:29
    at C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:724:13
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:356:16
    at replenish (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:877:25)
    at iterateeCallback (C:\Ariadna\proasistencia\node_modules\async\dist\async.js:867:17)
    at C:\Ariadna\proasistencia\node_modules\async\dist\async.js:840:16
    at Query._callback (C:\Ariadna\proasistencia\lib\contabilidad\contabilidad_db_mysql.js:720:17)
    at Query.Sequence.end (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\Ariadna\proasistencia\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
-------------------------------------------
 PROASISTENCIA RUNNING  21/03/02019 12:20:21
-------------------------------------------
 VERSION: 2.2.12
 PORT: 8080
-------------------------------------------
